traverse_directory: Avoid inconsistent use of PATH_MAX
Use of PATH_MAX causes this build error in Debian GNU/Hurd:
```
../desktop.c:366:47: error: ‘PATH_MAX’ undeclared (first use in this function)
  366 |                                 char new_path[PATH_MAX];
      |                                               ^~~~~~~~
```

See: https://buildd.debian.org/status/fetch.php?pkg=labwc-menu-generator&arch=hurd-amd64&ver=0.2.0-3&stamp=1784590565&raw=0

We could do an `#ifndef PATH_MAX` to define it in this case, but why not
use g_build_filename to avoid this altogether.

Additionally, we can use the return value of stat to skip the directory
on error.